name: Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-dotnet@v1

    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1

    - name: Nuget Add source 
      run: nuget sources Add -Name "GitHub" -Source "https://nuget.pkg.github.com/barimale/index.json" -UserName barimale -Password ${{ secrets.GITHUB_TOKEN }}
      
    - name: Nuget Restore 
      run: nuget restore .\ConfigurationManager.Api\ConfigurationManager.Api.sln

    - name: Build Solution 
      run: dotnet build .\ConfigurationManager.Api\ConfigurationManager.Api.sln --configuration Release

    - name: Nuget Pack
      run: nuget pack .\ConfigurationManager.Api\pack.nuspec -Properties Configuration=Release -OutputDirectory .\nugetPackages
      
    - name: Nuget Push
      run: nuget push .\nugetPackages\*.nupkg -Source GitHub 