name: Publish

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-dotnet@v1

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1

    - name: Nuget Add apiKey 
      run: nuget setapikey ${{ secrets.NUGET_ORG_TOKEN }} -Source "https://api.nuget.org/v3/index.json"

    - name: Nuget Restore 
      run: nuget restore .\ConfigurationManager.Api.sln

    - name: Build Solution 
      run: dotnet build .\ConfigurationManager.Api.sln --configuration Release

    - name: Nuget Pack
      run: nuget pack .\ConfigurationManager.Api\pack.nuspec -Properties Configuration=Release -OutputDirectory .\nugetPackages
    
    - name: Nuget Pack Symbols
      run: nuget pack .\ConfigurationManager.Api\pack.nuspec -Properties Configuration=Release -Symbols -OutputDirectory .\nugetPackages
    
    - name: Nuget Pack2
      run: nuget pack .\ConfigurationManager.Api\consul-pack.nuspec -Properties Configuration=Release -OutputDirectory .\nugetPackages
    
    - name: Nuget Pack2 Symbols
      run: nuget pack .\ConfigurationManager.Api\consul-pack.nuspec -Properties Configuration=Release -Symbols -OutputDirectory .\nugetPackages
    
    - name: Nuget Push
      run: nuget push .\nugetPackages\*.nupkg -Source "https://api.nuget.org/v3/index.json" -SkipDuplicate -NoSymbols
